version: "3.3"
services:
  nodeclient:
    container_name: nodeclient
    build:
      context: ""
      dockerfile: docker/cli/Dockerfile
    restart: always
    ports:
        - 4000:3000
    networks:
      - app-network
    volumes:
        - ./client/crypto-graph:/var/www/http/client
    depends_on:
      - nodeserv

  nodeserv:
    container_name: nestserv
    build:
      context: ""
      dockerfile: docker/serv/Dockerfile
    restart: always
    ports:
        - 4100:7100
    networks:
      - app-network
    volumes:
      - ./server/crypto-graph-serv:/var/www/http/server

#Docker Networks
networks:
  app-network:
    driver: bridge